/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */

import { Context, BaseClient } from "./core.js"
import {
  Container,
  Directory
} from "./client.gen.js"
import type {
  ID,
  Void
} from "./client.gen.js"


export type DatalatheBuildAndTestOpts = {
  source?: Directory // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L73)
}

export type DatalatheConcurrentReportTestOpts = {
  concurrency: number // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L532)
}

export type DatalatheIntegrationJavaOpts = {
  source?: Directory // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L612)
  javaClient: Directory // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L616)
}

export type DatalatheIntegrationJsOpts = {
  source?: Directory // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L553)
  jsClient: Directory // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L557)
}

export type DatalatheIntegrationPythonOpts = {
  source?: Directory // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L582)
  pythonClient: Directory // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L586)
}

export type DatalatheLoadTestOpts = {
  concurrency: number // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L511)
}

export type DatalatheMysqlStreamingMemoryPressureOpts = {
  cacheBust?: string // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L786)
}

export type DatalathePerfGateOpts = {
  rows: number // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L814)
  cacheBust?: string // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L817)
}

export type DatalathePublishOpts = {
  sessionToken?: Secret // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L116)
  endpointUrl?: string // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L117)
  version?: string // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L118)
  skipLatest?: boolean // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L119)
}

export type DatalathePushToEcrDirectOpts = {
  version?: string // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1604)
  skipLatest?: boolean // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1604)
}

export type DatalatheReleaseOpts = {
  sessionToken?: Secret // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1753)
  endpointUrl?: string // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1754)
  presignAccessKeyId?: Secret // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1755)
  presignSecretAccessKey?: Secret // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1756)
}

export type DatalatheReportPerfGateOpts = {
  iterations: number // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L886)
  concurrency: number // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L887)
  cacheBust?: string // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L890)
}

export type DatalatheScaleSoakOpts = {
  profile: string // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1119)
  reportRequestScoping: boolean // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1120)
}


export class Datalathe extends BaseClient { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L62)
  private readonly _id?: ID = undefined
  private readonly _buildAndTest?: Void = undefined
  private readonly _check?: string = undefined
  private readonly _clippy?: string = undefined
  private readonly _concurrentReportTest?: string = undefined
  private readonly _e2E?: string = undefined
  private readonly _e2EFilePartition?: string = undefined
  private readonly _e2EFilePartitionS3?: string = undefined
  private readonly _e2EMysql?: string = undefined
  private readonly _integrationJava?: string = undefined
  private readonly _integrationJs?: string = undefined
  private readonly _integrationPython?: string = undefined
  private readonly _loadTest?: string = undefined
  private readonly _memoryPressureTest?: string = undefined
  private readonly _multiEngineVerify?: string = undefined
  private readonly _mysqlStaleConnectionRetry?: string = undefined
  private readonly _mysqlStreamingBasic?: string = undefined
  private readonly _mysqlStreamingFailure?: string = undefined
  private readonly _mysqlStreamingKeyset?: string = undefined
  private readonly _mysqlStreamingLatinCharset?: string = undefined
  private readonly _mysqlStreamingMemoryPressure?: string = undefined
  private readonly _perfGate?: string = undefined
  private readonly _pushToEcrDirect?: string = undefined
  private readonly _registerCrossEnv?: string = undefined
  private readonly _reindexRebuild?: string = undefined
  private readonly _reportPerfGate?: string = undefined
  private readonly _scaleSoak?: string = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: ID,
     _buildAndTest?: Void,
     _check?: string,
     _clippy?: string,
     _concurrentReportTest?: string,
     _e2E?: string,
     _e2EFilePartition?: string,
     _e2EFilePartitionS3?: string,
     _e2EMysql?: string,
     _integrationJava?: string,
     _integrationJs?: string,
     _integrationPython?: string,
     _loadTest?: string,
     _memoryPressureTest?: string,
     _multiEngineVerify?: string,
     _mysqlStaleConnectionRetry?: string,
     _mysqlStreamingBasic?: string,
     _mysqlStreamingFailure?: string,
     _mysqlStreamingKeyset?: string,
     _mysqlStreamingLatinCharset?: string,
     _mysqlStreamingMemoryPressure?: string,
     _perfGate?: string,
     _pushToEcrDirect?: string,
     _registerCrossEnv?: string,
     _reindexRebuild?: string,
     _reportPerfGate?: string,
     _scaleSoak?: string,
   ) {
     super(ctx)

     this._id = _id
     this._buildAndTest = _buildAndTest
     this._check = _check
     this._clippy = _clippy
     this._concurrentReportTest = _concurrentReportTest
     this._e2E = _e2E
     this._e2EFilePartition = _e2EFilePartition
     this._e2EFilePartitionS3 = _e2EFilePartitionS3
     this._e2EMysql = _e2EMysql
     this._integrationJava = _integrationJava
     this._integrationJs = _integrationJs
     this._integrationPython = _integrationPython
     this._loadTest = _loadTest
     this._memoryPressureTest = _memoryPressureTest
     this._multiEngineVerify = _multiEngineVerify
     this._mysqlStaleConnectionRetry = _mysqlStaleConnectionRetry
     this._mysqlStreamingBasic = _mysqlStreamingBasic
     this._mysqlStreamingFailure = _mysqlStreamingFailure
     this._mysqlStreamingKeyset = _mysqlStreamingKeyset
     this._mysqlStreamingLatinCharset = _mysqlStreamingLatinCharset
     this._mysqlStreamingMemoryPressure = _mysqlStreamingMemoryPressure
     this._perfGate = _perfGate
     this._pushToEcrDirect = _pushToEcrDirect
     this._registerCrossEnv = _registerCrossEnv
     this._reindexRebuild = _reindexRebuild
     this._reportPerfGate = _reportPerfGate
     this._scaleSoak = _scaleSoak
   }

  /**
   * A unique identifier for this Datalathe.
   */
  id = async (): Promise<ID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<ID> = await ctx.execute()

    
    return response
  }

  /**
   * Build the application container
   */
  build = (source: Directory): Container => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1462)

    const ctx = this._ctx.select(
      "build",
      { source },
    )
    return new Container(ctx)
  }

  /**
   * Workspace check: the credential-free validation suite, sourced from the
   * module context so `dagger check` needs no arguments. A Workspace
   * constructor param would break cross-module consumers: workspace
   * arguments are not inherited by module runtime calls.
   */
  buildAndTest = async (
    opts?: DatalatheBuildAndTestOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L71) 
    ): Promise<void> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L71)
    if (this._buildAndTest) {
      return
    }

    const ctx = this._ctx.select(
      "buildAndTest",
      { ...opts},
    )

    await ctx.execute()

    
  }

  /**
   * Build macOS ARM binaries via cargo-zigbuild cross-compilation
   */
  buildDarwin = (source: Directory): Container => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1678)

    const ctx = this._ctx.select(
      "buildDarwin",
      { source },
    )
    return new Container(ctx)
  }

  /**
   * Create development environment container
   */
  buildEnv = (source: Directory): Container => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1651)

    const ctx = this._ctx.select(
      "buildEnv",
      { source },
    )
    return new Container(ctx)
  }

  /**
   * Credential-free validation: runs the workspace test suite and proves
   * the runner image assembles from the build artifacts. No registry push.
   */
  check = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L83)
    if (this._check) {
      return this._check
    }

    const ctx = this._ctx.select(
      "check",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  clippy = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L157)
    if (this._clippy) {
      return this._clippy
    }

    const ctx = this._ctx.select(
      "clippy",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * N concurrent /lathe/report queries against one staged chip — regression guard for runtime-thread starvation under load.
   */
  concurrentReportTest = async (source: Directory, 
    opts?: DatalatheConcurrentReportTestOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L527) 
    ): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L527)
    if (this._concurrentReportTest) {
      return this._concurrentReportTest
    }

    const ctx = this._ctx.select(
      "concurrentReportTest",
      { source, ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Export the cross-compiled darwin-arm64 binaries for smoke-testing
   * on a macOS runner before release publication
   */
  darwinBinaries = (source: Directory): Directory => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L147)

    const ctx = this._ctx.select(
      "darwinBinaries",
      { source },
    )
    return new Directory(ctx)
  }
  e2E = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L167)
    if (this._e2E) {
      return this._e2E
    }

    const ctx = this._ctx.select(
      "e2E",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Partitioned-staging e2e from a FILE source — splits one CSV into sub-chips by a column.
   */
  e2EFilePartition = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L187)
    if (this._e2EFilePartition) {
      return this._e2EFilePartition
    }

    const ctx = this._ctx.select(
      "e2EFilePartition",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Partitioned FILE staging against MinIO-backed chip storage — asserts every
   * sub-chip object AND its .meta.json sidecar land in the bucket, and the
   * sidecar's self-description matches the registered chip.
   */
  e2EFilePartitionS3 = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L209)
    if (this._e2EFilePartitionS3) {
      return this._e2EFilePartitionS3
    }

    const ctx = this._ctx.select(
      "e2EFilePartitionS3",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Chip lifecycle e2e from MYSQL source. Single-run only — the seeded MySQL fixture is shared mutable state.
   */
  e2EMysql = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L635)
    if (this._e2EMysql) {
      return this._e2EMysql
    }

    const ctx = this._ctx.select(
      "e2EMysql",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Run Java client integration tests against ephemeral engine + chip-manager.
   */
  integrationJava = async (
    opts?: DatalatheIntegrationJavaOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L607) 
    ): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L607)
    if (this._integrationJava) {
      return this._integrationJava
    }

    const ctx = this._ctx.select(
      "integrationJava",
      { ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Run JS client integration tests against ephemeral engine + chip-manager.
   */
  integrationJs = async (
    opts?: DatalatheIntegrationJsOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L548) 
    ): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L548)
    if (this._integrationJs) {
      return this._integrationJs
    }

    const ctx = this._ctx.select(
      "integrationJs",
      { ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Run Python client integration tests against ephemeral engine + chip-manager.
   */
  integrationPython = async (
    opts?: DatalatheIntegrationPythonOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L577) 
    ): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L577)
    if (this._integrationPython) {
      return this._integrationPython
    }

    const ctx = this._ctx.select(
      "integrationPython",
      { ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  loadTest = async (source: Directory, 
    opts?: DatalatheLoadTestOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L506) 
    ): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L506)
    if (this._loadTest) {
      return this._loadTest
    }

    const ctx = this._ctx.select(
      "loadTest",
      { source, ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Disk-spill regression test: forces the query engine to spill via memory_limit_mb=256 against a 100M-row sort.
   */
  memoryPressureTest = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1290)
    if (this._memoryPressureTest) {
      return this._memoryPressureTest
    }

    const ctx = this._ctx.select(
      "memoryPressureTest",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Proves two engine tasks share all state through chip-manager + S3: cross-engine
   * chip visibility, shared connection/license store, kill/resume of an async ingest,
   * and cross-engine delete. The un-pin gate for engine autoscaling.
   */
  multiEngineVerify = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L930)
    if (this._multiEngineVerify) {
      return this._multiEngineVerify
    }

    const ctx = this._ctx.select(
      "multiEngineVerify",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Buffered MySQL ingest must survive a stale cached connection — primes the cache, KILLs engine sessions, re-ingests.
   */
  mysqlStaleConnectionRetry = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L755)
    if (this._mysqlStaleConnectionRetry) {
      return this._mysqlStaleConnectionRetry
    }

    const ctx = this._ctx.select(
      "mysqlStaleConnectionRetry",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Streaming MySQL ingest happy-path against the existing MySQL service binding.
   */
  mysqlStreamingBasic = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L659)
    if (this._mysqlStreamingBasic) {
      return this._mysqlStreamingBasic
    }

    const ctx = this._ctx.select(
      "mysqlStreamingBasic",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Mid-stream failure: KILL the MySQL query during a streaming load, verify chip stays clean.
   */
  mysqlStreamingFailure = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L731)
    if (this._mysqlStreamingFailure) {
      return this._mysqlStreamingFailure
    }

    const ctx = this._ctx.select(
      "mysqlStreamingFailure",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Keyset-parallel streaming parity test — verify partition_column produces identical chip to serial.
   */
  mysqlStreamingKeyset = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L683)
    if (this._mysqlStreamingKeyset) {
      return this._mysqlStreamingKeyset
    }

    const ctx = this._ctx.select(
      "mysqlStreamingKeyset",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Streaming ingest survives latin1 text columns — regression for the nCino loan_origination 500.
   */
  mysqlStreamingLatinCharset = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L707)
    if (this._mysqlStreamingLatinCharset) {
      return this._mysqlStreamingLatinCharset
    }

    const ctx = this._ctx.select(
      "mysqlStreamingLatinCharset",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * 50M-row streaming load under memory_limit_mb=256. The nCino regression test.
   */
  mysqlStreamingMemoryPressure = async (source: Directory, 
    opts?: DatalatheMysqlStreamingMemoryPressureOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L779) 
    ): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L779)
    if (this._mysqlStreamingMemoryPressure) {
      return this._mysqlStreamingMemoryPressure
    }

    const ctx = this._ctx.select(
      "mysqlStreamingMemoryPressure",
      { source, ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Ingest perf gate at N rows under memory_limit_mb=256: buffered vs streaming vs keyset.
   * The engine runs inside the benchmark container so the script can read its peak RSS.
   * Emits PERF| timing lines and GATE| verdicts; fails on any threshold breach.
   */
  perfGate = async (source: Directory, 
    opts?: DatalathePerfGateOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L809) 
    ): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L809)
    if (this._perfGate) {
      return this._perfGate
    }

    const ctx = this._ctx.select(
      "perfGate",
      { source, ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Build, test, and push the runner image to ECR.
   */
  publish = async (source: Directory, awsAccount: string, awsRegion: string, awsRepo: string, secretAccessKey: Secret, accessKeyId: Secret, 
    opts?: DatalathePublishOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L106) 
    ): Promise<string[]> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L106)
    const ctx = this._ctx.select(
      "publish",
      { source, awsAccount, awsRegion, awsRepo, secretAccessKey, accessKeyId, ...opts},
    )

    const response: Awaited<string[]> = await ctx.execute()

    
    return response
  }
  pushToEcr = async (container: Container, awsAccount: string, awsRegion: string, awsRepo: string, awsCredentials: File): Promise<string[]> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1538)
    const ctx = this._ctx.select(
      "pushToEcr",
      { container, awsAccount, awsRegion, awsRepo, awsCredentials},
    )

    const response: Awaited<string[]> = await ctx.execute()

    
    return response
  }
  pushToEcrDirect = async (container: Container, args: DatalatheAwsArgs, 
    opts?: DatalathePushToEcrDirectOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1604) 
    ): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1604)
    if (this._pushToEcrDirect) {
      return this._pushToEcrDirect
    }

    const ctx = this._ctx.select(
      "pushToEcrDirect",
      { container, args, ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Cross-environment chip portability proof for POST /lathe/chips/register.
   * Two independent environments (own chip-manager + own bucket, shared MinIO):
   * stage a single chip and two partitioned families in A, then register from A
   * into B via a manifest. Asserts B lists and reports the imports through a
   * fresh attach, A is untouched, a re-register collides, a partial-family
   * manifest is rejected wholesale, and rename_to re-keys a single import.
   */
  registerCrossEnv = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L384)
    if (this._registerCrossEnv) {
      return this._registerCrossEnv
    }

    const ctx = this._ctx.select(
      "registerCrossEnv",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Disaster-recovery proof: stage chips (single + partitioned) into S3, wipe
   * the chip-manager metadata store, then rebuild the catalog from the bucket
   * with POST /lathe/chips/reindex and assert full recovery — chips listed
   * again with correct metadata and reports working from both a fresh engine
   * and the one that staged them.
   */
  reindexRebuild = async (source: Directory): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L291)
    if (this._reindexRebuild) {
      return this._reindexRebuild
    }

    const ctx = this._ctx.select(
      "reindexRebuild",
      { source},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }

  /**
   * Build release binaries for Linux x86_64 and macOS ARM, upload to S3, and send SNS notification
   */
  release = async (source: Directory, awsAccount: string, awsRegion: string, awsRepo: string, secretAccessKey: Secret, accessKeyId: Secret, version: string, s3Bucket: string, snsTopicArn: string, 
    opts?: DatalatheReleaseOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1740) 
    ): Promise<string[]> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1740)
    const ctx = this._ctx.select(
      "release",
      { source, awsAccount, awsRegion, awsRepo, secretAccessKey, accessKeyId, version, s3Bucket, snsTopicArn, ...opts},
    )

    const response: Awaited<string[]> = await ctx.execute()

    
    return response
  }

  /**
   * Report-path isolation perf gate: the same /lathe/report query under the
   * shared pool vs per-request instances, for 1 chip and a 3-chip table. The
   * engine runs inside the container and is restarted with report_request_scoping
   * flipped between models; every sequential sample is result-validated and a
   * cross-chip probe proves which model is active before measuring. Emits
   * PERF|/GATE| lines; gates the 1-3 chip added latency (p50 <= 25ms,
   * p95 <= 100ms over `iterations` samples; p99 reported, non-gating). The
   * concurrency phase is REPORTED, not gated: overload responses count as
   * failures instead of aborting, and effective QPS is computed over
   * successes at `concurrency` width per leg.
   */
  reportPerfGate = async (source: Directory, 
    opts?: DatalatheReportPerfGateOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L881) 
    ): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L881)
    if (this._reportPerfGate) {
      return this._reportPerfGate
    }

    const ctx = this._ctx.select(
      "reportPerfGate",
      { source, ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  run = (buildContainer: Container, source: Directory): Container => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1508)

    const ctx = this._ctx.select(
      "run",
      { buildContainer, source },
    )
    return new Container(ctx)
  }

  /**
   * Sustained mixed-load soak across the deployed two-engine topology,
   * exercising the recovery machinery (engine process kill + chip-manager
   * process bounce) UNDER continuous report/ingest/AI load. The un-pin gate
   * for raising the engine ceiling past 4.
   * 
   * One long-lived driver script drives every phase and triggers both recovery
   * events through markers on the shared volumes, so load never pauses across an
   * event. Engine A runs under a supervisor that SIGKILLs its process when the
   * driver touches the kill marker (a stable service address with the process
   * dead beneath it, connection-refused on 3000); chip-manager bounces beneath a
   * stable address through the same /cm-data/hold marker as multiEngineVerify.
   * The engine supervisor also redirects engine stdout to the shared volume (so
   * the driver can assert the admission_rejects metric lines) and samples the
   * engine cgroup memory every 15s.
   * 
   * profile "ci" (~25 min) is the weekly gate; "short" compresses the load
   * phases for a full local run. report_request_scoping defaults on (the
   * post-4.2 authoritative posture); pass false to soak the legacy
   * shared-pool rollback path.
   */
  scaleSoak = async (source: Directory, 
    opts?: DatalatheScaleSoakOpts // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1114) 
    ): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1114)
    if (this._scaleSoak) {
      return this._scaleSoak
    }

    const ctx = this._ctx.select(
      "scaleSoak",
      { source, ...opts},
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  test = (source: Directory): Container => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L1491)

    const ctx = this._ctx.select(
      "test",
      { source },
    )
    return new Container(ctx)
  }
}


export class DatalatheAwsArgs extends BaseClient { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L22)
  private readonly _id?: ID = undefined
  private readonly _accessKeyId?: string = undefined
  private readonly _awsAccount?: string = undefined
  private readonly _awsRegion?: string = undefined
  private readonly _awsRepo?: string = undefined
  private readonly _endpointUrl?: string = undefined
  private readonly _secretAccessKey?: string = undefined
  private readonly _sessionToken?: string = undefined

  /**
   * Constructor is used for internal usage only, do not create object from it.
   */
   constructor(
    ctx?: Context,
     _id?: ID,
     _accessKeyId?: string,
     _awsAccount?: string,
     _awsRegion?: string,
     _awsRepo?: string,
     _endpointUrl?: string,
     _secretAccessKey?: string,
     _sessionToken?: string,
   ) {
     super(ctx)

     this._id = _id
     this._accessKeyId = _accessKeyId
     this._awsAccount = _awsAccount
     this._awsRegion = _awsRegion
     this._awsRepo = _awsRepo
     this._endpointUrl = _endpointUrl
     this._secretAccessKey = _secretAccessKey
     this._sessionToken = _sessionToken
   }

  /**
   * A unique identifier for this DatalatheAwsArgs.
   */
  id = async (): Promise<ID> => {
    if (this._id) {
      return this._id
    }

    const ctx = this._ctx.select(
      "id",
    )

    const response: Awaited<ID> = await ctx.execute()

    
    return response
  }
  accessKeyId = async (): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L22)
    if (this._accessKeyId) {
      return this._accessKeyId
    }

    const ctx = this._ctx.select(
      "accessKeyId",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  awsAccount = async (): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L22)
    if (this._awsAccount) {
      return this._awsAccount
    }

    const ctx = this._ctx.select(
      "awsAccount",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  awsRegion = async (): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L22)
    if (this._awsRegion) {
      return this._awsRegion
    }

    const ctx = this._ctx.select(
      "awsRegion",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  awsRepo = async (): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L22)
    if (this._awsRepo) {
      return this._awsRepo
    }

    const ctx = this._ctx.select(
      "awsRepo",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  endpointUrl = async (): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L22)
    if (this._endpointUrl) {
      return this._endpointUrl
    }

    const ctx = this._ctx.select(
      "endpointUrl",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  secretAccessKey = async (): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L22)
    if (this._secretAccessKey) {
      return this._secretAccessKey
    }

    const ctx = this._ctx.select(
      "secretAccessKey",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
  sessionToken = async (): Promise<string> => { // datalathe (https://github.com/DataLathe/datalathe-backend/tree/d94b5053b738c72edc7bd63f3417fdf832e504f5/dagger/src/index.ts#L22)
    if (this._sessionToken) {
      return this._sessionToken
    }

    const ctx = this._ctx.select(
      "sessionToken",
    )

    const response: Awaited<string> = await ctx.execute()

    
    return response
  }
}


declare module "./client.gen.js" {
  interface Binding {
    asDatalathe(): Datalathe
    asDatalatheAwsArgs(): DatalatheAwsArgs
  }
  interface Env {
    withDatalatheAwsArgsInput(name: string, value: DatalatheAwsArgs, description: string): Env
    withDatalatheAwsArgsOutput(name: string, description: string): Env
    withDatalatheInput(name: string, value: Datalathe, description: string): Env
    withDatalatheOutput(name: string, description: string): Env
  }
  interface Client {
    datalathe(): Datalathe
  }
}

import type {
  Client as __Client,
  Binding as __Binding,
  Env as __Env
} from "./client.gen.js"

export function __applyDatalatheAugmentations(scope: {
  Client: typeof __Client
  Binding: typeof __Binding
  Env: typeof __Env
}) {
  const { Client, Binding, Env } = scope
  type Client = __Client
  type Binding = __Binding
  type Env = __Env

Binding.prototype.asDatalathe = function (this: any): Datalathe {

    const ctx = this._ctx.select(
      "asDatalathe",
    )
    return new Datalathe(ctx)
}

Binding.prototype.asDatalatheAwsArgs = function (this: any): DatalatheAwsArgs {

    const ctx = this._ctx.select(
      "asDatalatheAwsArgs",
    )
    return new DatalatheAwsArgs(ctx)
}

Env.prototype.withDatalatheAwsArgsInput = function (this: any, name: string, value: DatalatheAwsArgs, description: string): Env {

    const ctx = this._ctx.select(
      "withDatalatheAwsArgsInput",
      { name, value, description },
    )
    return new Env(ctx)
}

Env.prototype.withDatalatheAwsArgsOutput = function (this: any, name: string, description: string): Env {

    const ctx = this._ctx.select(
      "withDatalatheAwsArgsOutput",
      { name, description },
    )
    return new Env(ctx)
}

Env.prototype.withDatalatheInput = function (this: any, name: string, value: Datalathe, description: string): Env {

    const ctx = this._ctx.select(
      "withDatalatheInput",
      { name, value, description },
    )
    return new Env(ctx)
}

Env.prototype.withDatalatheOutput = function (this: any, name: string, description: string): Env {

    const ctx = this._ctx.select(
      "withDatalatheOutput",
      { name, description },
    )
    return new Env(ctx)
}

Client.prototype.datalathe = function (this: any): Datalathe {

    const ctx = this._ctx.select(
      "datalathe",
    )
    return new Datalathe(ctx)
}
}